### ISSUE TITLE
MongoDB exporter gets some metrics but Grafana dashboard does not display them

### ISSUE THREAD

**Issue by Kenya-West** [percona/mongodb_exporter#1020]
**Describe the bug**
Noobie here.
I successfully setup multi-target MongoDB exporter and got metrics by target URL in Prometheus but there is no data in Grafana dashboards. Used [this](https://github.com/percona/grafana-dashboards/blob/main/dashboards/MongoDB/MongoDB_Cluster_Summary.json) and [this](https://github.com/percona/grafana-dashboards/blob/main/dashboards/MongoDB/MongoDB_Instance_Summary.json) one.

**To Reproduce**
1. Setup docker-compose.yml:
```yaml
---
services:
  mongodb_exporter:
    image: percona/mongodb_exporter:0.43.1
    container_name: mongodb_exporter
    cpus: 0.5
    mem_limit: 200m
    env_file:
      - .env
    networks:
      - caddy

networks:
  caddy:
    external: true
```

2. In `.env`, set hosts to collect data from as following:
```dotenv
MONGODB_URI=mongodb+srv://user:password@cluster6.9texege.mongodb.net/admin
```

3. Add Prometheus config record:

```yaml
  - job_name: MongoDB
    file_sd_configs:
    - files:
      - /etc/file_sd/mongodb_targets_custom.yml
      refresh_interval: 30s
```

4. Setup `mongodb_targets_custom.yml`:

```yaml
- targets:
  - mongodb_exporter:9216
  labels:
    __metrics_path__: /scrape
    __param_target: cluster6.9texege.mongodb.net
```

5. See green `🟩 UP` status in Prometheus and check metrics manually by HTTP:
```sh
/ # wget -O- http://mongodb_exporter:9216/scrape?target=cluster6.9texege.mongodb.net | tail -n 12
Connecting to mongodb_exporter:9216 (172.18.0.13:9216)
writing to stdout
-                    100% |**************************************************|  8471  0:00:00 ETA
written to stdout
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.8643328e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.73835338716e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.279807488e+09
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

6. Add [this](https://github.com/percona/grafana-dashboards/blob/main/dashboards/MongoDB/MongoDB_Cluster_Summary.json) or [this](https://github.com/percona/grafana-dashboards/blob/main/dashboards/MongoDB/MongoDB_Instance_Summary.json) one of dashboards in Grafana

**Expected behavior**
I should see some bars, charts and data.

**Environment**
 - MongoDB exporter 0.43.1
 - Ubuntu 24.04
 - Docker the latest
 - MongoDB version 8.0.4
