### ISSUE TITLE
Need clarification about permissions for PBM Metrics

### ISSUE THREAD

**Issue by pawellrus** [percona/mongodb_exporter#1039]
Hello.
Permissions that shown in documentation are not enough to fetch pbm mertrics.
I had to give to exporter's account permissions like pbm's account

```
          - resource:
              anyResource: true
            actions:
              - anyAction
```

Is it only way to get pbm metrics, or there is possibility to decrease permissions scope?
