### ISSUE TITLE
v0.40+ Fails to Connect to MongoDB with "server selection error: context deadline exceeded"

### ISSUE THREAD

**Issue by dkinmongo** [percona/mongodb_exporter#1079]
I'm encountering a connection issue with `percona/mongodb_exporter` versions 0.40 and above when connecting to a MongoDB container in a Docker environment. The exporter works fine with version 0.39 but fails with versions 0.40, 0.41, 0.42, 0.43, and 0.44, throwing a "server selection error: context deadline exceeded" error.

## Environment
- **MongoDB**: `mongo:7.0.18`
- **Exporter**: `percona/mongodb_exporter:0.40` (and higher)
- **Docker Compose**: Both containers are on the same bridged network (`monitoring`)
- **MongoDB URI**: `mongodb://admin:password@mongodb:27017`
- **Command Flags**: `--collect-all`, `--compatible-mode`, `--log.level=debug`

## Issue
When using `percona/mongodb_exporter:0.39`, the exporter connects successfully and exposes metrics at `http://localhost:9216/metrics`. However, starting with version 0.40, it fails to connect to MongoDB, producing the following error:

> time="2025-05-07T07:43:44Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: context deadline exceeded, current topology: { Type: Single, Servers: [{ Addr: mongodb:27017, Type: Unknown }, ] }"

For versions 0.41 and 0.42, an additional error appears:

> time="2025-05-07T07:48:51Z" level=error msg="Registry - Cannot get node type to check if this is a mongos : cannot get mongo node type from an empty client"

## Docker Compose Configuration
```yaml
services:
  mongodb:
    image: mongo:7.0.18
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - monitoring

  mongodb_exporter:
    image: percona/mongodb_exporter:0.40
    container_name: mongodb_exporter
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
    command:
      - "--collect-all"
      - "--compatible-mode"
      - "--log.level=debug"
    depends_on:
      - mongodb
    networks:
      - monitoring

volumes:
  mongodb_data:

networks:
  monitoring:
    driver: bridge
```

The issue persists across versions 0.40 to 0.44 but does not occur with 0.39.
This issue seems similar to [#767](https://github.com/percona/mongodb_exporter/issues/767), but it occurs with a minimal setup, suggesting a change in behavior starting from version 0.40.
Has anyone encountered and resolved this issue with mongodb_exporter versions 0.40+?

Thanks in advance for any insights or suggestions!
