### ISSUE TITLE
PMM-8489 Failed to get topology labels when the target server is mongos

### ISSUE THREAD

**Issue by JamesChenX** [percona/mongodb_exporter#296]
## Steps to Reproduce
1. Set up a mongos server
2. Update the `mongodb.uri` to the mongos and run mongodb_exporter

## Actual
Failed to get topology labels when the target server is mongos, and get the error from logs:
> time="2021-06-14T08:39:16Z" level=error msg="Cannot get topology info: error getting cluster ID: (CommandNotFound) no such cmd: replSetGetConfig: cannot get topology labels"

## Expected
Should work fine with mongos

## Note
It seems the error is caused by: https://github.com/percona/percona-toolkit/blob/49b570ed0ccb49cecd3515d444f3fef44a56d115/src/go/mongolib/util/util.go#L460
because it's not a `ReplicationNotEnabledError` but a `CommandNotFound` error.

## Example
```yaml
  mongo-exporter:
    image: bitnami/mongodb-exporter:0.20.5
    command:
      - '--disable.replicasetstatus'
    depends_on:
      - mongodb-router
    environment:
      - MONGODB_URI=mongodb://mongodb-router:27017
    restart: always
    ports:
      - 9216:9216

  mongodb-router:
    image: "bitnami/mongodb-sharded:4.4.4"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-router
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
```
