### ISSUE TITLE
How can I run this in kubernetes?

### ISSUE THREAD

**Issue by jaya-rama** [percona/mongodb_exporter#346]

**Comment by denisok** [comment]
we have a feature waiting to be implemented #265. Theoretically you could prepare container by yourself and run it as a sidecar container.

**Comment by jonaskint** [comment]
Another approach for this could be something similar on how Istio does it's Envoy sidecar injection. They work with a configmap that specifies the actual sidecar template. The percona mongodb operator could then add those based on the labels that are attached to the statefulsets that run a mongo cluster.

**Comment by kaykhan** [comment]
Can anyone help me with creating a confguration on how to add this as a sidecar to the prometheus mongodb operator. There is some documentation on how to define a sidecar - https://docs.percona.com/percona-operator-for-mongodb/sidecar.html

Im fairly new to this, so other than setting the image: `percona/mongodb_exporter:0.36` is there anything else i need to do?

**Comment by denisok** [comment]
@kaykhan if you want to monitor it with Percona operator for MongoDB - please consider PMM. Operator already have a sidecar for that.

In you example, you need to change the command, as well as args. You also need to specify port to open so extrenal prometheus could query exporter.

```
spec:
  replsets:
    sidecars:
    - image: percona/mongodb_exporter:0.37
      command: ["/mongodb_exporter"] 
      args: ["--mongodb.uri=mongodb://127.0.0.1:17001"] 
      ports:
      - exporter: 9216
      name: rs-sidecar-0
```

something like that but I didn't verify it.
