### ISSUE TITLE
MongoDB on Docker connection refused

### ISSUE THREAD

**Issue by kristianfzr** [percona/mongodb_exporter#403]
Hi there,

I am using MongoDB on docker, image `mongo:4.0`. There is no user name or password configuration and the docker container is set to `--bind_ip 0.0.0.0`, so I can connect directly on 127.0.0.1:27017. The MongoDB server is working as it should. But as I try to run the mongodb-exporter the following error appears:

`time="2022-01-07T07:44:22Z" level=info msg="Starting HTTP server for http://:9216/metrics ..." source="server.go:140"
time="2022-01-07T07:44:52Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: 127.0.0.1:27017, Type: Unknown, Last error: connection() error occured during connection handshake: dial tcp 127.0.0.1:27017: connect: connection refused }, ] }"`

I did check some of the issues in the project but I could not find a solution, I don't think the roles apply here as there is no user in general. Is there anything that I am doing wrong since the mongodb is on docker as well?

**Comment by percona-csalguero** [comment]
Hi, 

It is hard to say the reason of this error.
The project has its own sandbox with the same conditions you mention and the exporter is able to connect.
Could you provide the docker-compose.yml file or a way to reproduce it?

Thanks.

**Comment by kristianfzr** [comment]
Hi,

I did manage to connect it. I had the same issues with a nginx exporter, its network related. The production setup is in a replicaSet but before that I was testing locally with 2 containers. One is a MongoDB docker container and the other is the exporter. For a setup  I have a compose file for the mongodb:
```
version: "2.0"
services:
    mongo:
        image: mongo:5.0
        logging:
            options:
                max-size: "12m"
                max-file: "5"
            driver: json-file
        ports:
            - "27017:27017"
        volumes:
            - ${PWD}/data/mongo:/data/db
        restart: always
        command: mongod --bind_ip 0.0.0.0

```
Then I used your example command and added `--network host`. 
`sudo docker run -d -p 9216:9216 -p 17001:17001 --restart=always --name=mongodb-exporter --network host percona/mongodb_exporter:0.20 --mongodb.uri=127.0.0.1:27017`

That connected without issues I saw the metrics in the prometheus over port 9216. Is there a dashboard that you have as an example that I can use?
