### ISSUE TITLE
collecting mongdb cluster indicator data is missing

### ISSUE THREAD

**Issue by chj9** [percona/mongodb_exporter#423]
### For example
**MongoDB Instances Overview > Total Used Mapped Memory**
mongodb_ss_mem_mapped
mongodb_ss_mem_mapped_with_journal
![image](https://user-images.githubusercontent.com/16426260/151332312-bd6e2fb5-7574-47e1-988e-eb12712d442f.png)

**MongoDB Cluster Summary > QPS of Mongos Service**
rate(mongodb_op_counters_total{service_name="router-45",type!="command"}[10s])
![image](https://user-images.githubusercontent.com/16426260/151332118-f244a623-1b3b-4ce2-a9cc-ae2e30acc2ec.png)

### My k8s pod config
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: mongodb-exporter-router-0
  name: mongodb-exporter-router-0
  namespace: mongodb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mongodb-exporter-router-0
  template:
    metadata:
      labels:
        k8s-app: mongodb-exporter-router-0
    spec:
      containers:
        - args:
            - --log.level=info
            - --compatible-mode 
            - --mongodb.global-conn-pool
            - --mongodb.collstats-colls=turnright.*,turnrightForEncrypt.*,turnrightForVipQA2.*,turnrightForQA.*,turnrightForVip.*
            - --mongodb.indexstats-colls=turnright.*,turnrightForEncrypt.*,turnrightForVipQA2.*,turnrightForQA.*,turnrightForVip.*
            - --discovering-mode
            - --collector.dbstats
          env:
            - name: MONGODB_URI
              value: "mongodb://172.17.20.45:27017/"
          image: percona/mongodb_exporter:0.30.0
          imagePullPolicy: IfNotPresent
          name: mongodb-exporter
          ports:
            - containerPort: 9216
      restartPolicy: Always
```
