### ISSUE TITLE
mongodb.collstats-colls is not giving any output or error

### ISSUE THREAD

**Issue by amulrajd** [percona/mongodb_exporter#432]
**Describe the bug**
mongodb.collstats-colls option is not working in docker-compose setup

**To Reproduce**
1. what parameters are being passed to `mongodb_exporter` 
"--mongodb.global-conn-pool", "--compatible-mode", "--collector.dbstats", "--discovering-mode",  "--mongodb.collstats-colls=db1.col1,db1.col2"

2. describe steps to reproduce the issue
create docker-compose.yml file with below content
version: "2.4"
volumes:
  grafana:
    external: true

services:

  mongodb:
    image: mongo:5.0.6
    command: [ "mongod" ]
    ports:
      - "27017:27017"
    volumes:
      - /home/data:/data/db:rw

  mongo_exporter_prometheus:
    image: percona/mongodb_exporter:0.30.0
    command: [ "--mongodb.global-conn-pool", "--compatible-mode", "--collector.dbstats", "--discovering-mode",  "--mongodb.collstats-colls=db1.col1,db1.col2" ]
    environment:
      MONGODB_URI: mongodb://mongodb:27017
  
    ports:
      - "9216:9216"

docker-compose up -d
create 3 collections with 10 documents in each collection in mongodb
curl -s localhost:9216/metrics |grep -v \#|grep -i db1.col1

**Expected behavior**
mongodb_mongod_db_coll_count{coll="col1",db="db1"} 10
mongodb_mongod_db_coll_count{coll="col2",db="db1"} 10

**Logs**
time="2022-02-04T16:36:25Z" level=info msg="Starting HTTP server for http://:9216/metrics ..." source="server.go:140"

**Environment**
 - Ubuntu 20.04.3 LTS
 - environment (docker)
 - MongoDB version 5.0.6

**Additional context**
tried enabling mongodb authentication and creating roles, still the same problem

Count of Total documents in the DB is displayed properly
mongodb_mongod_db_objects_total{cl_id="",cl_role="",database="db1",rs_state="0"} 30

But, not the count of documents from the individual collection

**Comment by ShashankSinha252** [comment]
Hi @amulrajd . Thanks for reporting the issue.

We have found a compatibility bug in our exporter codebase. The call to MongoDB for retrieving collection statistics (**$collStats**) works for versions 4.2 and 4.4, but fails for 5.0.

To reproduce issue, one can run the exporter with log level set as `debug` and connect to MongoDB 5.0 instance. If collection statistics are requested by exporter, one can notice error in logs, such as:
```
ERRO[0001] cannot get $collstats cursor for collection db1.col2: (Location40415) BSON field '$collStats.latencyStats.key' is an unknown field. ```

**Comment by amulrajd** [comment]
@ShashankSinha252 
Could you please tell me what parameters need to be passed to the mongodb exporter and the mongodb , to get the following output ? I'm still not getting the expected metrics to create a grafana dashboard
```
mongodb_mongod_db_coll_count{coll="hr",db="test"} 5
mongodb_mongod_db_coll_count{coll="empoyee",db="test"} 5
```

Here is what I tried with no luck,
docker.compose.yml
```
version: "3.3"
services:
  mongodb:
    image: mongo:5.0.6
    command: ["mongod"]
    volumes:
      - /tmp/mongo:/data/db:rw
    ports:
      - "27017:27017"

  mongo_exporter_prometheus:
    image: percona/mongodb_exporter:0.32.0
    command: [ "--mongodb.global-conn-pool", "--discovering-mode", "--compatible-mode", "--collector.topmetrics", "--collector.dbstats", "--mongodb.collstats-colls=test.hr,test.customer,test.employee" ]
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    ports:
      - "9216:9216"

```

Mongo shell
`> db
test
> show collections
customers
employee
hr
> db.employee.count()
5
> db.employee.find()
{ "_id" : ObjectId("62693da9cf617902e30a8575"), "first_name" : "employee1" }
{ "_id" : ObjectId("62693daccf617902e30a8576"), "first_name" : "employee2" }
{ "_id" : ObjectId("62693daecf617902e30a8577"), "first_name" : "employee3" }
{ "_id" : ObjectId("62693db0cf617902e30a8578"), "first_name" : "employee4" }
{ "_id" : ObjectId("62693db3cf617902e30a8579"), "first_name" : "employee5" }
> 

`
