### ISSUE TITLE
Mongodb_exporter export only one mongodb metric ( --collect-all is on)

### ISSUE THREAD

**Issue by DamienGH** [percona/mongodb_exporter#621]
Hi, 

I have an issue with mongodb_exporter. I think it's because of a configuration problem in my side but after 2 days of searching I'm empty of solution

**Describe the bug**
I run mongodb on K8S and mongodb_exporter as a sidecar pod.
exporter starts OK (I think, because no error), display some metrics but my problem is that's only "go" metrics (see below), I have just one "mongodb" metric!! => mongodb_up 1. Even if i put options "--collect-all" or "--collector.collstats".

- Connection to the database is OK because if I change username/password/db port I ran to connection problem.
- My user have correct rights I think (changing real password to "password" in all my reporting) : 
```
Successfully added user: {
        "user" : "exporter",
        "roles" : [
                {
                        "role" : "clusterMonitor",
                        "db" : "admin"
                },
                {
                        "role" : "read",
                        "db" : "local"
                }
        ]
}
```

**To Reproduce**
Don't know if you can reproduce with that but here is my pod configuration : 
```
        - name: metrics
          image: docker.io/bitnami/mongodb-exporter:latest
          command:
            - /bin/bash
            - '-ec'
          args:
            - >
              /bin/mongodb_exporter --web.listen-address ":9216"
              --mongodb.uri=mongodb://exporter:password@localhost:27017/config? --log.level="debug"  --collect-all
          ports:
            - name: metrics
              containerPort: 9216
              protocol: TCP
          env:
          resources:
            limits:
              cpu: 50m
              memory: 250Mi
            requests:
              cpu: 25m
              memory: 50Mi
          livenessProbe:
            httpGet:
              path: /
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
```

**Expected behavior**
I want to see mongodb metrics, such as collection metrics

**Logs**
- Exporter start log (with debug activated) : 
```
time="2023-02-03T09:02:25Z" level=debug msg="Compatible mode: false"
time="2023-02-03T09:02:25Z" level=debug msg="Connection URI: mongodb://exporter:password@localhost:27017/config?"
level=info ts=2023-02-03T09:02:25.224Z caller=tls_config.go:195 msg="TLS is disabled." http2=false
```

- Displayed metrics : 
```
# HELP collector_scrape_time_ms Time taken for scrape by collector
# TYPE collector_scrape_time_ms gauge
collector_scrape_time_ms{collector="general",exporter="mongodb"} 0
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 17
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.17.13"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 3.655088e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 3.655088e+06
[....]
# HELP mongodb_up Whether MongoDB is up.
# TYPE mongodb_up gauge
mongodb_up 1
[...]
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.35940608e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

**Environment**
 - K8S
 - MongoDB version : 4.2.0

Thanks in advance for any help :)

**Comment by KESNERO** [comment]
I have the same problem, if you have any solution please share it

**Comment by rusk0** [comment]
I've also been struggling with this same  behavior
exporter = 0.37
mongodb = 4.4.18

**Comment by JMLX42** [comment]
The following docker-compose configuration works for me:

```yml
    mongodb_exporter:
        image: percona/mongodb_exporter:0.37.0
        networks:
            - mongodb
            - prometheus
        restart: unless-stopped
        depends_on:
            - mongodb
        command:
            - '--mongodb.uri=mongodb://test_user:test_password@mongodb:27017'
            - '--compatible-mode'
            - '--collect-all'
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
```
