### ISSUE TITLE
Reconsider inclusion of opid in mongodb_currentop_query_uptime

### ISSUE THREAD

**Issue by nick-jones** [percona/mongodb_exporter#746]
**Describe the bug**

PR #706 introduced `mongodb_currentop_query_uptime`, which is derived from the results of `db.currentOp()`. The labels used here include `opid`. I don't know how `opid` is generated, but from what I've observed so far, `opid` appears to be distinct for every single executed operation. The general recommendation is to avoid high cardinality labels, as the inclusion of these can be problematic - https://prometheus.io/docs/practices/naming/#labels

`connid` may also cause problems, depending on how that is generated mongodb side and general connection patterns.

**To Reproduce**
Run the exporter against a mongodb instance that sees at least some traffic, and observe how the number of unique `mongodb_currentop_query_uptime` combinations grown over time. Something like `sum(count_over_time(mongodb_currentop_query_uptime[30d]))` may help visualise the growth in datapoints.

**Expected behavior**
Prometheus documentation recommends avoiding high cardinality labels, so `opid` should perhaps not be included.

**Logs**
N/A

**Environment**
 - OS: Linux
 - environment: k8s
 - MongoDB version: 5.0.10

**Additional context**
N/A

**Comment by tregubov-av** [comment]
Hello.
This metric is not intended for plotting.
The data depends on the scrape interval.
You will not see requests that were completed between taking this metric.
The metric is intended exclusively for building notifications that have been in the process of execution for too long.
For example:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: kube-prometheus-stack
  name: mongodb-rules
  namespace: ${NAMESPACE}
spec:
  groups:
  - name: mongodb.rules
    rules:
    ## Slow query alerts
    # 5 minutes trigger, E-mail + Slack (critical)
    - alert: MongodbCurrentQueryTime
      labels:
        severity: critical
        database: mongo
      expr: (mongodb_currentop_query_uptime > 3e+8) / 1000
      annotations:
        summary: "{{ $labels.endpoint }}: slow query detected"
        description_email: |
          Opid: {{ $labels.opid }}<br/>
          Uptime: {{ $value }}ms<br/>
          Ns: <strong>{{ $labels.ns }}</strong><br/>
          Desc: {{ $labels.desc }}<br/>
          Op: {{ $labels.op }}<br/>
        description_slack: |
          *Opid:* `{{ $labels.opid }}`
          *Uptime:* `{{ $value }}ms`
          *Ns:* {{ $labels.ns }}
          *Desc:* `{{ $labels.desc }}`
          *Op:* {{ $labels.op }}
    # 1 minute trigger, E-mail (warning)
    - alert: MongodbCurrentQueryTime
      labels:
        severity: warning
        database: mongo
      expr: (mongodb_currentop_query_uptime > 6e+7) / 1000
      annotations:
        summary: "{{ $labels.endpoint }}: slow query detected"
        description_email: |
          Opid: {{ $labels.opid }}<br/>
          Uptime: {{ $value }}ms<br/>
          Ns: <strong>{{ $labels.ns }}</strong><br/>
          Desc: {{ $labels.desc }}<br/>
          Op: {{ $labels.op }}<br/>
 ```
 Unfortunately, there is no other way to track a request that is in progress.
 
 If you are worried about an overabundance of data in the Prometheus database, then I think the following solution may be appropriate:
You can enter a variable (for example, CurrentOpSlowTime) that will limit the entries to only those time values ​​to which we will react.
https://github.com/percona/mongodb_exporter/blob/main/exporter/currentop_collector.go

for example:

```
if microsecs_running >= CurrentOpSlowTime {
  break
}
```
