### ISSUE TITLE
collstats metrics for shard cluster is incomplete

### ISSUE THREAD

**Issue by abelite-fang** [percona/mongodb_exporter#824]
**Describe the bug**
We are using mongodb_exporter on our shard cluster via SRV record, the collstats metrics like  mongodb_collstats_storageStats_count{} return single shard count, and there is no label to identify which shard it is.

**To Reproduce**
1. Parameters:
```yaml
serviceMonitor:
  enabled: true
  interval: 10s
  scrapeTimeout: 9s
  additionalLabels:
    release: prometheus-operator
  metricRelabelings:
    - targetLabel: cl_name
      replacement: core

existingSecret:
  name: "prometheus-mongodb-exporter"
  key: "mongodb-uri"

extraArgs:
  - --collector.indexstats
  - --collector.collstats
  - --collector.collstats-limit=0
  - --collect-all=true
  - --discovering-mode=true
  - --no-mongodb.direct-connect
```

2. connection string set to SRV record, and designate collection label to a sharded collection, exporter will only return single shard collstats.

**Expected behavior**
Expect to have collstats (e.g. document counts, logical data size, etc.) for each shard on a sharded cluster, identify by shard name (replicaset name) or any other label.

**Logs**
no relevance error log.

**Environment**
 - environment: Kubernetes (EKS)
 - MongoDB Atlas (managed), version: 5.0.25
 - helm chart: prometheus-community/prometheus-mongodb-exporter version 3.5.0
 - image: percona/mongodb_exporter:0.40.0
