### ISSUE TITLE
Missing mongodb_version_info metrics in --no-compatible-mode

### ISSUE THREAD

**Issue by BeckYeh** [percona/mongodb_exporter#856]
**Describe the bug**
mongodb_version_info will miss if start with option --no-compatible-mode. and I can't find the same metrics

**To Reproduce**
helm chart deploy like
```yaml
mongodb:
  uri: mongodb://user:pass@localhost:27017/?ssl=false&replicaSet=my_name&authSource=admin,mongodb://user:pass@localhost:27018/?ssl=false&replicaSet=my_name&authSource=admin,mongodb://user:pass@localhost:27019/?ssl=false&replicaSet=my_name&authSource=admin
extraArgs:
  - --collector.diagnosticdata
  - --collector.replicasetstatus
  - --discovering-mode
  - --collector.topmetrics
  - --log.level=warn
  - --mongodb.global-conn-pool
  - --no-compatible-mode
serviceMonitor:
  enabled: false
resources:
  limits:
    cpu: 800m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 318Mi
```
