### ISSUE TITLE
mongodb-instance-summary dashboard not displaying metric data

### ISSUE THREAD

**Issue by kaykhan** [percona/mongodb_exporter#868]
**Describe the bug**

I have kube-prometheus-stack deployed on my kubernetes cluster.  I have percona mongodb server + operator running within this cluster. I have setup mongodb_exporter as a sidecar. I have also installed the dashboards by firstly converting them using `convert-dash-from-PMM.py`.

However i can see the dashboard `mongodb-instance-summary` is not loading any data.

( i can see i have yet to install that one plugin ) 
![image](https://github.com/percona/mongodb_exporter/assets/5202527/0c1df03c-b4af-4ebe-9822-2f75d16633ca)

In Comparison the mongodb-instances-overview dashboard does show data. 

![image](https://github.com/percona/mongodb_exporter/assets/5202527/923698f6-4190-4498-bb45-7455ef19507f)

**To Reproduce**

1. Install latest version of percona mongodb operator + server https://docs.percona.com/percona-operator-for-mongodb/index.html.

2. Attach mongodb-exporter as a side car using the following params.

```
        sidecars:
          - image: percona/mongodb_exporter:0.40
            name: metrics 
            env:
            - name: EXPORTER_USER
              valueFrom:
                secretKeyRef:
                  name: psmdb-db-internal-secrets
                  key: MONGODB_CLUSTER_MONITOR_USER
            - name: EXPORTER_PASS
              valueFrom:
                secretKeyRef:
                  name: psmdb-db-internal-secrets
                  key: MONGODB_CLUSTER_MONITOR_PASSWORD
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MONGODB_URI
              value: "mongodb://$(EXPORTER_USER):$(EXPORTER_PASS)@[$(POD_IP)]:27017"
            args: ["--discovering-mode", "--compatible-mode", "--collect-all", "--mongodb.uri=$(MONGODB_URI)"]
```

3. Convert the dashboard and then install onto grafana instance. 

```
python convert-dash-from-PMM.py ../dashboards/MongoDB/MongoDB_Instance_Summary.json
```

**Expected behavior**
I expect this dashboard to have data as it use to do.

**Logs**
N/A

**Environment**
 - OS,
 - environment (docker, k8s, etc):  `EKS 1.30`
 - MongoDB: `7`

**Additional context**
