### ISSUE TITLE
v0.41.0 http panic on scrape

### ISSUE THREAD

**Issue by Deshke** [percona/mongodb_exporter#913]
```
mongodb-exporter-1  | 2024/09/18 08:19:00 http: panic serving 10.0.23.73:39496: descriptor Desc{fqName: "collector_scrape_time_ms", help: "Time taken for scrape by collector", constLabels: {collector="profile"}, variableLabels: {exporter}} already exists with the same fully-qualified name and const label values
mongodb-exporter-1  | goroutine 9518 [running]:
mongodb-exporter-1  | net/http.(*conn).serve.func1()
mongodb-exporter-1  | 	/opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:1903 +0xbe
mongodb-exporter-1  | panic({0xd1c980?, 0xc000bf6bd0?})
mongodb-exporter-1  | 	/opt/hostedtoolcache/go/1.22.7/x64/src/runtime/panic.go:770 +0x132
mongodb-exporter-1  | github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(...)
mongodb-exporter-1  | 	/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/registry.go:405
mongodb-exporter-1  | github.com/percona/mongodb_exporter/exporter.(*Exporter).makeRegistry(0xc0006b26c0, {0x13934f8, 0xc00023c000}, 0xc0001b0620, {0x13901b8, 0xc000f02990}, {{0xc00050fc80, 0x1, 0x1}, 0x0, ...})
mongodb-exporter-1  | 	/home/runner/work/mongodb_exporter/mongodb_exporter/exporter/exporter.go:247 +0xc19
mongodb-exporter-1  | github.com/percona/mongodb_exporter/exporter.RunWebServer.(*Exporter).Handler.func2({0x1392720, 0xc0001b00e0}, 0xc0000ea240)
mongodb-exporter-1  | 	/home/runner/work/mongodb_exporter/mongodb_exporter/exporter/exporter.go:376 +0x6cf
mongodb-exporter-1  | net/http.HandlerFunc.ServeHTTP(0x19c6f40?, {0x1392720?, 0xc0001b00e0?}, 0x7fa63a?)
mongodb-exporter-1  | 	/opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:2171 +0x29
mongodb-exporter-1  | net/http.(*ServeMux).ServeHTTP(0x471859?, {0x1392720, 0xc0001b00e0}, 0xc0000ea240)
mongodb-exporter-1  | 	/opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:2688 +0x1ad
mongodb-exporter-1  | net/http.serverHandler.ServeHTTP({0xc000dd8690?}, {0x1392720?, 0xc0001b00e0?}, 0x6?)
mongodb-exporter-1  | 	/opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:3142 +0x8e
mongodb-exporter-1  | net/http.(*conn).serve(0xc0004ba120, {0x1393450, 0xc0004b0390})
mongodb-exporter-1  | 	/opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:2044 +0x5e8
mongodb-exporter-1  | created by net/http.(*Server).Serve in goroutine 52
mongodb-exporter-1  | 	/opt/hostedtoolcache/go/1.22.7/x64/src/net/http/server.go:3290 +0x4b4
```

```yaml
  exporter:
    image: percona/mongodb_exporter:0.41.0
    restart: always
    network_mode: "host"
    volumes:
      - /storage/mongodb/secrets:/secrets
    command: "--discovering-mode --collect-all --log.level=info --no-mongodb.direct-connect"
    environment:
      - MONGODB_URI=mongodb://root_user:xxxx@node1:27020,node2:27020,node3:27020/admin?ssl=true&tlsCertificateKeyFile=secrets/node.pem&tlsCAFile=secrets/ca.crt
```
