### ISSUE TITLE
pbm_collector is logging the mongo URI with user credentials in plain text

### ISSUE THREAD

**Issue by rd790-gh** [percona/mongodb_exporter#950]
**Describe the bug**
When `/exporter/pbm_collector.go` [fails](https://github.com/percona/mongodb_exporter/blob/main/exporter/pbm_collector.go#L86) to create PBM client from the URI, it is logging the mongo URI with user credentials in plain text. `pbm_collector.go` was introduced in 0.41.2.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy mongodb_exporter as a sidecar, using the percona psmdb-db helm chart for deployment with the following config. 

```
sidecars: 
- image: percona/mongodb_exporter:0.42.0
  env:
  - name: MONGODB_USER
    valueFrom:
      secretKeyRef:
        name: percona-mongodb-test-secrets
        key: MONGODB_CLUSTER_MONITOR_USER
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: percona-mongodb-test-secrets
        key: MONGODB_CLUSTER_MONITOR_PASSWORD
  - name: MONGODB_URI
    value: "mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@localhost:27017?authSource=admin&replicaSet=rs0"
  args: ["--mongodb.direct-connect", "--web.listen-address=:9216", "--compatible-mode", "--collect-all", "--mongodb.uri=$(MONGODB_URI)"]
  name: metrics
```

**Expected behavior**
Mongo URI logged with user credentials sanitised. 

**Logs**
`time="2024-11-05T16:56:54Z" level=error msg="failed to create PBM client from uri mongodb://USERNAME:PASSWORD@127.0.0.1:27017: create mongo connection: ping: server selection error: context deadline exceeded, current topology: { Type: Unknown, Servers: [{ Addr: 127.0.0.1:27017, Type: RSGhost, Average RTT: 374386 }, ] }" collector=pbm`

**Environment**
 - Amazon Linux
 - K8s, EKS, 1.29
 - MongoDB version 7.0.14-8
 - mongodb_exporter version 0.41.2
 

**Additional context**
I've actually been unable to get this working and always receive this log, I'm currently running 0.40.0 to avoid this logging credentials to our logging stack. However, I can't say if there is a problem with the code, or it's something I'm doing wrong.
