### ISSUE TITLE
Issue with MongoDB Exporter Connection to the MongoDB Instance

### ISSUE THREAD

**Issue by asemarian** [percona/mongodb_exporter#951]
I'm using the Percona Operator for MongoDB to deploy a MongoDB cluster on Kubernetes. I'm trying to add a sidecar container running `mongodb_exporter` to collect metrics. Here is my current configuration for the sidecar:

```yaml
sidecars:
  - args:
      - --mongodb.uri=mongodb://mongodb-cluster-a9901-mongodb-replicaset.mongodb-cluster.svc.cluster.local:27017
    env:
      - name: MONGODB_USER
        value: clusterAdmin
      - name: MONGODB_PASSWORD
        value: clusterAdminPassword
    image: percona/mongodb_exporter:0.42
    name: exporter
    ports:
      - containerPort: 9216
        name: metrics
```
Note that:
- The MongoDB cluster is already up and running with other applications successfully connected to it.
- I’m setting the `--mongodb.uri` argument to connect to the MongoDB instance.
- I included the port in the URI, though I’m not sure if it’s necessary.
- I'm using environment variables to pass `MONGODB_USER` and `MONGODB_PASSWORD` for the clusterAdmin role.

The problem is that the exporter cannot connect to the MongoDB instance. Here's the logs:
```
time="2024-10-31T13:58:07Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: mongodb://mongodb-cluster-a9901-mongodb-replicaset.mongodb-cluster.svc.cluster.local:27017, Type: Unknown, Last error: dial tcp: lookup mongodb://mongodb-cluster-a9901-mongodb-replicaset.mongodb-cluster.svc.cluster.local on 10.43.0.10:53: no such host }, ] }"
```

I'd appreciate any insights you can offer into why the exporter is failing to connect. 

Thank you.
