### ISSUE TITLE
release 0.43 - 10x increase in memory usage (~50Mb -> ~500Mb)

### ISSUE THREAD

**Issue by blushingpenguin** [percona/mongodb_exporter#990]
**Describe the bug**
Release 0.43 increases the memory usage of the metrics container dramatically compared to 0.42

**To Reproduce**
Just switching the container version reproduces consistently

**Expected behavior**
Similar memory usage

**Logs**
![image](https://github.com/user-attachments/assets/aea1bfd1-6da5-454a-8df2-6dc7c242c1a0)

On the LHS is v0.40, the middle is 0.43, the RHS is 0.42

**Environment**
This is a percona operator for mongodb managed deployment of mongo 7.0.15 running on microk8s 1.31 on ubuntu 24.04

**Comment by BupycHuk** [comment]
Hi, could you share more details about cluster being monitored. 
Is it sharded cluster or just replicaset?
Is it mongos, mongod, arbiter or config node?
Did you enable all collectors?
Can you build mongodb_exporter from main and check if the problem fixed on your side? We recently faced similar problem with Mongo 8 and improved performance a bit, but we are not sure that it will fix your problem.

**Comment by blushingpenguin** [comment]
Hi, thanks for the swift response.

We have basic mongo replica set with 3 x mongod. (We have 5 mongo clusters which have similar config and I saw the same problem on all of them).

The config for the exporter is:

```yaml
sidecars:
- image: percona/mongodb_exporter:0.42 # 0.43
  env:
  - name: EXPORTER_USER
    valueFrom:
      secretKeyRef:
        name: mongo-psmdb-db-secrets
        key: MONGODB_CLUSTER_MONITOR_USER
  - name: EXPORTER_PASS
    valueFrom:
      secretKeyRef:
        name: mongo-psmdb-db-secrets
        key: MONGODB_CLUSTER_MONITOR_PASSWORD
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: MONGODB_URI
    value: "mongodb://$(EXPORTER_USER):$(EXPORTER_PASS)@$(POD_IP):27017"
  args: ["--discovering-mode", "--compatible-mode", "--collect-all", "--log.level=debug", "--mongodb.uri=$(MONGODB_URI)"]
  name: metrics
```

I can have a go at building a container, are there some instructions on how to do so? I'm not familiar with go.
